# app.yaml
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: ubuntu22

env_variables:
  DB_STRING: 'postgresql+psycopg2://postgres:Pozuelo1@/hatttrick_db?host=/cloudsql/hattrick-428116:us-central1:hatttrickdb
beta_settings:
  cloud_sql_instances: hattrick-428116:us-central1:hatttrickdb

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
